Shopping Cart Presistence
Tiewhan/FeistyCommonFiles pull request #34
Opened 2020-04-24 12:21 UTC by Tiewhan

<h1>Overview</h1>
Added persistence logic to the shopping cart allowing the user to add items to the cart that will stay when the user closes the application

<h2>Additions Made</h2>
Added a repository for the shopping cart.
Added observers and observables to the view-model and model for the shopping cart.

2020-04-24 12:23 UTC, Tiewhan commented on Source/CoreDataFiles/CoreDataAppDelegate.swift
> +//
This is essentially a wrapper that the app delegate in the main project must conform to. It just allows the dev pod to make use of the app delegate without needing to depend on the main project

2020-04-24 12:25 UTC, XanderSchoeman requested changes
Just check that bitrise status checks* can pass. Then ill approve.

2020-04-24 18:27 UTC, JancoDVTDev approved these changes
Code looks clean and easy to read.

2020-04-27 08:06 UTC, Zamo22 commented on Source/ShoppingCart/Repositories/ShoppingCartCoreDataRepo.swift
> +    } catch { }
Empty catch here, can we either handle it or use try? with a guard let

2020-04-28 08:57 UTC, XanderSchoeman approved these changes

2020-04-28 09:06 UTC, merged